import React,{useEffect,useMemo,useState}from"react";
import ReactDOM from"react-dom/client";
import{createClient}from"genlayer-js";
import{studionet}from"genlayer-js/chains";
import{TransactionStatus,type Hash}from"genlayer-js/types";
import"./styles.css";

declare global{interface Window{ethereum?:{request:(x:{method:string})=>Promise<string[]>}}}
type Order={order_id:number;policy_id:number;policy_authority:string;policy_url:string;policy_version:string;policy_digest:string;merchant:string;buyer:string;order_ref:string;product_code:string;purchase_time:string;request_time:string;usage_units:number;refund_amount:string|number;held:string|number;paid_buyer:string|number;paid_merchant:string|number;state:string;outcome:string;cited_clause_ids:string[];reason_codes:string[]};
const EXPLORER="https://explorer-studio.genlayer.com";
const DEPLOYED_CONTRACT="0x5Ea83Be7737a63B57543d00CD2bFB92De4Ef2f96";

function App(){
 const initialOrder=new URLSearchParams(location.search).get("order")||"0";
 const[account,setAccount]=useState(""),[contract,setContract]=useState(localStorage.getItem("pvs.v2.contract")||DEPLOYED_CONTRACT),[orderId,setOrderId]=useState(initialOrder),[record,setRecord]=useState<Order|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("Loading the verified v2 contract from StudioNet…"),[journal,setJournal]=useState<{label:string;hash:string}[]>([]);
 const[url,setUrl]=useState(""),[version,setVersion]=useState("REFUND-V2"),[digest,setDigest]=useState(""),[policyId,setPolicyId]=useState("0"),[buyer,setBuyer]=useState(""),[orderRef,setOrderRef]=useState("ORDER-001"),[product,setProduct]=useState("DIGITAL-SERVICE"),[amount,setAmount]=useState("1"),[units,setUnits]=useState("1");
 const readClient=useMemo(()=>createClient({chain:studionet}),[]),valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
 async function connect(){if(!window.ethereum)return setMessage("No injected wallet found.");try{const a=await window.ethereum.request({method:"eth_requestAccounts"});if(!a[0])throw new Error("No account selected");const c=createClient({chain:studionet,provider:window.ethereum,account:a[0] as`0x${string}`});await c.connect("studionet");setAccount(a[0]);setMessage(`Connected ${a[0]}. The connected wallet signs only its own role transactions.`)}catch(e){setMessage(e instanceof Error?e.message:"Wallet connection cancelled")}}
 function saveContract(v:string){v=v.trim();setContract(v);localStorage.setItem("pvs.v2.contract",v);setRecord(null)}
 async function readRaw(method:string,args:(string|number)[]=[]){if(!valid)throw new Error("Enter the deployed v2 contract address first.");return String(await readClient.readContract({address:contract as`0x${string}`,functionName:method,args}))}
 async function load(target=orderId){if(!/^\d+$/.test(target))throw new Error("Order ID must be a non-negative integer.");const raw=await readRaw("get_order",[Number(target)]);if(raw==="NOT_FOUND")throw new Error("Order not found.");const parsed=JSON.parse(raw) as Order;setRecord(parsed);return parsed}
 async function read(){setBusy("read");try{const meta=JSON.parse(await readRaw("get_contract_version"));if(meta.name!=="PolicyVersionSentinel"||meta.version!==2)throw new Error("This address is not the v2 authority-funded escrow contract.");await load();setMessage("Loaded contract v2 and authoritative on-chain order state.")}catch(e){setMessage(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
 useEffect(()=>{if(valid)void read()},[]);
 async function write(label:string,method:string,args:(string|number)[],value=0n){if(!valid||!account||!window.ethereum)return setMessage("Enter the deployed v2 contract address and connect the wallet for this role.");setBusy(method);try{const meta=JSON.parse(await readRaw("get_contract_version"));if(meta.name!=="PolicyVersionSentinel"||meta.version!==2)throw new Error("Contract schema mismatch: v2 is required.");let target=orderId,before=-1;const counts=JSON.parse(await readRaw("get_counts"));if(method==="create_policy"){before=counts.policy_count}else if(method==="create_funded_order"){before=counts.order_count;target=String(before)}const client=createClient({chain:studionet,provider:window.ethereum,account:account as`0x${string}`});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as`0x${string}`,functionName:method,args,value}));setJournal(x=>[{label,hash},...x]);setMessage(`${label} signed. Waiting for finality and reading chain state…`);const receipt=await readClient.waitForTransactionReceipt({hash:hash as Hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(receipt.resultName!=="MAJORITY_AGREE"){if(/^\d+$/.test(target))await load(target).catch(()=>{});throw new Error(`${label} finalized as ${receipt.resultName||"UNKNOWN_RESULT"}; the UI does not claim it succeeded.`)}if(receipt.txExecutionResultName&&receipt.txExecutionResultName!=="FINISHED_WITH_RETURN"){if(/^\d+$/.test(target))await load(target).catch(()=>{});throw new Error(`${label} execution result: ${receipt.txExecutionResultName}. Chain state reloaded.`)}if(method==="create_policy"){const after=JSON.parse(await readRaw("get_counts")).policy_count;if(after!==before+1)throw new Error("Finalized, but policy count did not advance.");setPolicyId(String(before));setMessage(`Policy ${before} created by ${account}. Record this ID for the funded order.`)}else if(method==="create_funded_order"){const after=JSON.parse(await readRaw("get_counts")).order_count;if(after!==before+1)throw new Error("Finalized, but order count did not advance.");setOrderId(target);await load(target);setMessage(`Order ${target} funded and read back from chain.`)}else{await load(target);setMessage(`${label} finalized. The state below is authoritative chain readback.`)}}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const canMerchant=!!account&&!!record&&account.toLowerCase()===record.merchant.toLowerCase(),canBuyer=!!account&&!!record&&account.toLowerCase()===record.buyer.toLowerCase(),fund=Number(amount)>0&&Number.isSafeInteger(Number(amount));
 return <><header><a href="#top" className="brand"><img src="/policy-sentinel-logo.png"/><span><b>PolicyVersion Sentinel</b><small>Merchant-authorized · funded · source-bound</small></span></a><nav><a href="#how">How it works</a><a href="#operate">Operate</a><a href="#evidence">Evidence</a></nav><span className="network">● StudioNet · v2</span><button onClick={connect}>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></header><main id="top">
 <section className="hero"><div><p className="eyebrow">SIGNED POLICY AUTHORITY · CHAIN-RECORDED FACTS · REAL ESCROW</p><h1>Refund terms,<br/><em>bound to proof.</em></h1><p>A merchant wallet signs its exact policy source and funds each order’s refund amount. The contract records order timing and usage, and an independent GenLayer assessment can route escrow to buyer or merchant.</p><div className="chips"><span>01 Merchant signs policy</span><span>02 Merchant funds order</span><span>03 Buyer requests review</span><span>04 Contract settles</span></div></div><div className="hero-card"><img src="/policy-sentinel-logo.png"/><small>CONSEQUENTIAL OUTCOMES</small><b>ELIGIBLE → REFUND BUYER</b><b>INELIGIBLE → RELEASE MERCHANT</b><b>AMBIGUOUS → KEEP ESCROW HELD</b></div></section>
 <section className="how" id="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>Authenticity at the boundary. Judgment only where needed.</h2><p>Wallet signatures establish who accepted each role in this contract—not an external legal identity attestation.</p></div><ol><li><span>01</span><p><b>Merchant publishes & signs policy</b><br/>Create a policy pointer with HTTPS URL, version and digest. The sender wallet becomes that policy’s authority.</p></li><li><span>02</span><p><b>Merchant funds an order</b><br/>The same authority records buyer, product, order reference and exact refund amount, sending matching native value into escrow.</p></li><li><span>03</span><p><b>Parties record facts on-chain</b><br/>Merchant records usage; only the buyer can request a refund. Purchase and request times come from chain transaction context.</p></li><li><span>04</span><p><b>Consensus routes custody</b><br/>Public adjudication re-fetches the committed source and returns bounded, cited reasons. Eligible returns funds to buyer; ineligible pays merchant; ambiguous stays held.</p></li></ol></section>
 <section className="contract"><label>Deployed v2 contract<input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="Paste the newly deployed v2 address"/></label><label>Order ID<input value={orderId} onChange={e=>setOrderId(e.target.value)}/></label><button disabled={!valid||!!busy} onClick={read}>Load v2 order</button></section>
 <section className="operate" id="operate"><article><p className="eyebrow">01 · POLICY AUTHORITY WALLET</p><h2>Commit policy source</h2><p className="hint">Connect the merchant/policy-authority wallet. This signature binds authority to subsequent order funding.</p><div className="grid"><label className="wide">Public HTTPS policy source<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…/refund-policy-v2.txt"/></label><label>Policy version<input value={version} onChange={e=>setVersion(e.target.value)}/></label><label>SHA-256 digest<input value={digest} onChange={e=>setDigest(e.target.value)} placeholder="64 hex characters"/></label></div><button className="primary" disabled={!valid||!account||!!busy||!url.startsWith("https://")||!/^[0-9a-fA-F]{64}$/.test(digest)} onClick={()=>write("Create policy","create_policy",[url,version,digest])}>Sign & register policy</button><p className="hint">Digest must equal SHA-256 of the exact bounded source text from POLICY_START through POLICY_END.</p></article>
 <article><p className="eyebrow">02 · SAME MERCHANT WALLET</p><h2>Fund a distinct order</h2><div className="grid"><label>Policy ID<input value={policyId} onChange={e=>setPolicyId(e.target.value)}/></label><label>Buyer wallet<input value={buyer} onChange={e=>setBuyer(e.target.value)} placeholder="Independent buyer 0x…"/></label><label>Order reference<input value={orderRef} onChange={e=>setOrderRef(e.target.value)}/></label><label>Product / plan code<input value={product} onChange={e=>setProduct(e.target.value)}/></label><label className="wide">Refund escrow amount · base units<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><button className="primary" disabled={!valid||!account||!!busy||!fund||!/^\d+$/.test(policyId)||!/^0x[0-9a-fA-F]{40}$/.test(buyer)||buyer.toLowerCase()===account.toLowerCase()} onClick={()=>write("Create funded order","create_funded_order",[Number(policyId),buyer,orderRef,product,Number(amount)],BigInt(amount||"0") )}>Fund order escrow</button><p className="hint">Transaction value must exactly match the recorded refund amount. Use the wallet that registered this policy.</p></article></section>
 <section className="decision"><div><p className="eyebrow">03 · MERCHANT RECORDS SERVICE USAGE</p><h2>Record delivered usage</h2><p>Only the order’s merchant can append usage while the order is funded. The refund-review facts are read from contract state, not claimant-entered text.</p><label className="field-label">Usage units<input inputMode="numeric" value={units} onChange={e=>setUnits(e.target.value)}/></label><button className="accent" disabled={!valid||!account||!!busy||!record||!canMerchant||record.state!=="FUNDED"||!/^\d+$/.test(units)} onClick={()=>write("Record usage","record_usage",[Number(orderId),Number(units)])}>Record on-chain usage</button></div><div><p className="eyebrow">04 · BUYER REQUESTS · PUBLIC ADJUDICATION</p><h2>Request review and settle</h2><p>The independent buyer requests review. Anyone may trigger assessment and settlement, but only the finalized adjudication result selects the recipient.</p><button className="secondary" disabled={!valid||!account||!!busy||!record||!canBuyer||record.state!=="FUNDED"} onClick={()=>write("Request refund","request_refund",[Number(orderId)])}>Request refund review</button><button className="accent" disabled={!valid||!account||!!busy||!record||record.state!=="REFUND_REQUESTED"} onClick={()=>write("Adjudicate order","adjudicate",[Number(orderId)])}>Run source-bound adjudication</button><button className="secondary" disabled={!valid||!account||!!busy||!record||!record.state.startsWith("REVIEW_")} onClick={()=>write("Settle escrow","settle",[Number(orderId)])}>Settle escrow by result</button></div></section>
 <section className="readback" id="evidence"><div className="read-head"><div><p className="eyebrow">AUTHORITATIVE CHAIN READBACK · ORDER {record?.order_id??"—"}</p><h2>{record?.order_ref||"No order loaded"}</h2></div><span className={`status ${record?.outcome||""}`}>{record?.state||"NOT LOADED"}</span></div><div className="facts"><div><small>Merchant / policy authority</small><b>{record?.merchant||"—"}</b></div><div><small>Independent buyer</small><b>{record?.buyer||"—"}</b></div><div><small>Product code</small><b>{record?.product_code||"—"}</b></div><div><small>Purchase timestamp · chain</small><b>{record?.purchase_time||"—"}</b></div><div><small>Request timestamp · chain</small><b>{record?.request_time||"Not requested"}</b></div><div><small>Usage units · merchant tx</small><b>{record?.usage_units??"—"}</b></div><div><small>Escrow held</small><b>{record?.held??"—"}</b></div><div><small>Paid buyer / merchant</small><b>{record?`${record.paid_buyer} / ${record.paid_merchant}`:"—"}</b></div><div><small>Policy version · digest</small><b>{record?`${record.policy_version} · ${record.policy_digest}`:"—"}</b></div><div><small>Grounded clause IDs</small><b>{record?.cited_clause_ids.join(", ")||"—"}</b></div><div><small>Bounded reason codes</small><b>{record?.reason_codes.join(", ")||"—"}</b></div><div><small>Exact committed source</small>{record?<a href={record.policy_url} target="_blank" rel="noreferrer">Open policy source ↗</a>:<b>—</b>}</div></div><p className="boundary">Authority means control of the wallet that registered and funded this policy/order. It does not verify a merchant’s off-chain legal identity. The adjudication is bounded to one funded order and one digest-bound policy snapshot.</p>{record&&<p><a href={`${EXPLORER}/address/${contract}`} target="_blank" rel="noreferrer">Contract explorer ↗</a></p>}</section>
 <section className="message"><b>Protocol status</b><p>{message}</p></section><section className="journal" id="transactions"><p className="eyebrow">TRANSACTION PROOF · CLICK TO OPEN EXPLORER</p><h2>Finalized writes from this browser</h2>{journal.length?journal.map(x=><a key={x.hash} href={`${EXPLORER}/tx/${x.hash}`} target="_blank" rel="noreferrer"><b>{x.label}</b><code>{x.hash.slice(0,14)}…{x.hash.slice(-8)}</code><span>View transaction ↗</span></a>):<p>After you sign a transaction, its finalized hash appears here with a direct explorer link.</p>}</section></main><footer><img src="/policy-sentinel-logo.png"/><b>PolicyVersion Sentinel v2</b><p>Wallet-bound authority. Chain-sourced facts. Real settlement.</p>{valid&&<a href={`${EXPLORER}/address/${contract}`} target="_blank" rel="noreferrer">View contract ↗</a>}</footer></>}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
