import React,{useEffect,useMemo,useState}from"react";
import ReactDOM from"react-dom/client";
import{createClient}from"genlayer-js";
import{studionet}from"genlayer-js/chains";
import{TransactionStatus,type Hash}from"genlayer-js/types";
import"./styles.css";

declare global{interface Window{ethereum?:{request:(x:{method:string})=>Promise<string[]>}}}
type Claim={claim_id:number;claimant:string;acknowledger:string;snapshot_id:number;claim:{claim_ref:string;purchase_date:string;request_date:string;event:string;requested_remedy:string;facts:string[]};claim_digest:string;policy_url:string;policy_version:string;policy_digest:string;state:string;outcome:string;cited_clause_ids:string[];reason_codes:string[]};
const EXPLORER="https://explorer-studio.genlayer.com";
const POLICY_URL="https://raw.githubusercontent.com/dearmore5382/PolicyVersionSentinel/main/samples/refund-policy-v1.txt";
const DEPLOYED_CONTRACT="0x97E92D2784d26ac14dCFE6215F7Ede582DA1608F";

function App(){
 const initialClaim=new URLSearchParams(location.search).get("claim")||"0";
 const[account,setAccount]=useState(""),[contract,setContract]=useState(localStorage.getItem("pvs.contract")||DEPLOYED_CONTRACT),[snapshotId,setSnapshotId]=useState("3"),[claimId,setClaimId]=useState(initialClaim),[record,setRecord]=useState<Claim|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("Loading authoritative StudioNet state…");
 const[url,setUrl]=useState(POLICY_URL),[version,setVersion]=useState("REFUND-2026-01"),[digest,setDigest]=useState("484cf05dafedd618e83329a9080b74ed028e30819f3b2560d7bac3dc8736a394"),[effective,setEffective]=useState("2026-01-01"),[acknowledger,setAcknowledger]=useState(""),[ref,setRef]=useState("PVS-DEMO-001"),[purchase,setPurchase]=useState("2026-09-20"),[request,setRequest]=useState("2026-09-25"),[event,setEvent]=useState("Service purchased but not consumed"),[remedy,setRemedy]=useState("Full refund"),[facts,setFacts]=useState("Request filed 5 days after purchase\nNo service usage recorded"),[journal,setJournal]=useState<{label:string;hash:string}[]>([]);
 const readClient=useMemo(()=>createClient({chain:studionet}),[]),valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
 async function connect(){if(!window.ethereum)return setMessage("No injected wallet found.");try{const a=await window.ethereum.request({method:"eth_requestAccounts"});if(!a[0])throw new Error("No account selected");const c=createClient({chain:studionet,provider:window.ethereum,account:a[0] as`0x${string}`});await c.connect("studionet");setAccount(a[0]);setMessage("Wallet connected. The deployer has no workflow privilege.")}catch(e){setMessage(e instanceof Error?e.message:"Wallet connection cancelled")}}
 function saveContract(v:string){v=v.trim();setContract(v);localStorage.setItem("pvs.contract",v);setRecord(null)}
 async function load(target=claimId){if(!valid||!/^\d+$/.test(target))throw new Error("Set a valid contract and claim ID");const raw=String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_claim",args:[Number(target)]}));if(raw==="NOT_FOUND")throw new Error("Claim not found");const parsed=JSON.parse(raw)as Claim;setRecord(parsed);return parsed}
 async function read(){setBusy("read");try{await load();setMessage("Authoritative claim state loaded.")}catch(e){setMessage(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
 useEffect(()=>{void read()},[]);
 async function write(label:string,method:string,args:(string|number)[]){if(!valid||!account||!window.ethereum)return setMessage("Set contract and connect wallet first.");setBusy(method);try{const meta=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_contract_version",args:[]})));if(meta.name!=="PolicyVersionSentinel"||meta.version!==1)throw new Error("Contract schema mismatch");let target=claimId,before=-1;if(method==="file_claim"){before=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_counts",args:[]}))).claim_count;target=String(before)}const client=createClient({chain:studionet,provider:window.ethereum,account:account as`0x${string}`});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as`0x${string}`,functionName:method,args,value:0n}));setJournal(x=>[{label,hash},...x]);setMessage("Signed. Waiting for finality and authoritative readback...");const receipt=await readClient.waitForTransactionReceipt({hash:hash as Hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(receipt.resultName!=="MAJORITY_AGREE"){if(method!=="register_snapshot"&&/^\d+$/.test(target))await load(target);throw new Error(`${label} finalized as ${receipt.resultName||"UNKNOWN_RESULT"}; no successful state transition is claimed.`)}if(receipt.txExecutionResultName&&receipt.txExecutionResultName!=="FINISHED_WITH_RETURN"){if(method!=="register_snapshot"&&/^\d+$/.test(target))await load(target);throw new Error(`${label} execution result: ${receipt.txExecutionResultName}. Authoritative state was reloaded.`)}if(method==="file_claim"){const after=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_counts",args:[]}))).claim_count;if(after!==before+1)throw new Error("Finalized but claim count did not advance");setClaimId(target);await load(target)}else if(method!=="register_snapshot")await load(target);setMessage(`${label} finalized with MAJORITY_AGREE. Read authoritative state below.`)}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const claim=JSON.stringify({schema:"refund-claim-v1",claim_ref:ref,purchase_date:purchase,request_date:request,event,requested_remedy:remedy,facts:facts.split("\n").map(x=>x.trim()).filter(Boolean)});
 return <><header><a href="#top" className="brand"><img src="/policy-sentinel-logo.png"/><span><b>PolicyVersion Sentinel</b><small>Version-bound refund review</small></span></a><nav><a href="#how">How it works</a><a href="#operate">Operate</a><a href="#evidence">Evidence</a></nav><span className="network">● StudioNet</span><button onClick={connect}>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></header><main id="top">
 <section className="hero"><div><p className="eyebrow">EXACT VERSION · GROUNDED CLAUSES · BOUNDED OUTCOME</p><h1>Policies change.<br/><em>Evidence should not.</em></h1><p>Bind one refund claim to one exact public policy snapshot. Validators cite the clauses they used; deterministic contract logic protects roles, commitments and replay.</p><div className="chips"><span>01 Snapshot</span><span>02 Claim</span><span>03 Adjudicate</span><span>04 Acknowledge</span></div></div><div className="hero-card"><img src="/policy-sentinel-logo.png"/><small>BOUNDED DECISION SPACE</small><b>ELIGIBLE</b><b>INELIGIBLE</b><b>AMBIGUOUS</b></div></section>
 <section className="how" id="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>Four actions. No deployer privilege.</h2></div><ol><li><span>01</span><p><b>Register snapshot</b><br/>Any wallet commits a public HTTPS policy URL, version and bounded-content digest.</p></li><li><span>02</span><p><b>File claim</b><br/>A claimant locks facts and nominates a different acknowledger.</p></li><li><span>03</span><p><b>Adjudicate</b><br/>Validators refetch the policy, verify commitments and cite grounded clauses.</p></li><li><span>04</span><p><b>Acknowledge</b><br/>Only the nominated wallet confirms receipt of the exact result; no funds move.</p></li></ol></section>
 <section className="contract"><label>Active contract<input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="0x… deployed with primary wallet"/></label><label>Claim ID<input value={claimId} onChange={e=>setClaimId(e.target.value)}/></label><button disabled={!valid||!!busy} onClick={read}>Load state</button></section>
 <section className="operate" id="operate"><article><p className="eyebrow">01 · PUBLIC SNAPSHOT</p><h2>Bind the policy version</h2><div className="grid"><label className="wide">Policy HTTPS URL<input value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Version<input value={version} onChange={e=>setVersion(e.target.value)}/></label><label>Effective date<input value={effective} onChange={e=>setEffective(e.target.value)}/></label><label className="wide">Bounded policy SHA-256<input value={digest} onChange={e=>setDigest(e.target.value)} placeholder="64 lowercase hex characters"/></label></div><button className="primary" disabled={!valid||!account||!!busy||!/^([0-9a-f]{64})$/.test(digest)} onClick={()=>write("Register snapshot","register_snapshot",[url,version,digest,effective])}>Register policy snapshot</button><p className="hint">Digest exactly the text from POLICY_START through POLICY_END, including both markers.</p></article>
 <article><p className="eyebrow">02 · CLAIMANT WALLET</p><h2>Lock a refund claim</h2><div className="grid"><label>Snapshot ID<input value={snapshotId} onChange={e=>setSnapshotId(e.target.value)}/></label><label>Acknowledger wallet<input value={acknowledger} onChange={e=>setAcknowledger(e.target.value)} placeholder="Different wallet 0x…"/></label><label>Claim reference<input value={ref} onChange={e=>setRef(e.target.value)}/></label><label>Purchase date<input value={purchase} onChange={e=>setPurchase(e.target.value)}/></label><label>Request date<input value={request} onChange={e=>setRequest(e.target.value)}/></label><label>Requested remedy<input value={remedy} onChange={e=>setRemedy(e.target.value)}/></label><label className="wide">Event<input value={event} onChange={e=>setEvent(e.target.value)}/></label><label className="wide">Facts, one per line<textarea value={facts} onChange={e=>setFacts(e.target.value)}/></label></div><button className="primary" disabled={!valid||!account||!!busy||!/^\d+$/.test(snapshotId)||!/^0x[0-9a-fA-F]{40}$/.test(acknowledger)} onClick={()=>write("File claim","file_claim",[Number(snapshotId),acknowledger,claim])}>File immutable claim</button></article></section>
 <section className="decision"><div><p className="eyebrow">03 · PERMISSIONLESS CONSENSUS</p><h2>Adjudicate exact claim</h2><p>Any funded StudioNet wallet may request consensus. Only bounded outcomes and grounded clause IDs persist.</p><button className="accent" disabled={!valid||!account||!!busy||!/^\d+$/.test(claimId)||record?.state!=="CLAIM_FILED"} onClick={()=>write("Adjudicate claim","adjudicate_claim",[Number(claimId)])}>Run policy adjudication</button></div><div><p className="eyebrow">04 · NAMED ACKNOWLEDGER</p><h2>Acknowledge result</h2><p>Exact claim and policy commitments are rechecked. Acknowledgement records receipt; it does not promise or transfer a refund.</p><button className="secondary" disabled={!record||!account||!!busy||!record.state.startsWith("REVIEW_")} onClick={()=>record&&write("Acknowledge result","acknowledge",[record.claim_id,record.claim_digest,record.policy_digest])}>Acknowledge exact result</button></div></section>
 <section className="readback" id="evidence"><div className="read-head"><div><p className="eyebrow">AUTHORITATIVE READBACK</p><h2>{record?.claim.claim_ref||"No claim loaded"}</h2></div><span className={`status ${record?.outcome||""}`}>{record?.state||"PENDING"}</span></div><div className="facts"><div><small>Policy version</small><b>{record?.policy_version||"—"}</b></div><div><small>Policy digest</small><b>{record?.policy_digest||"—"}</b></div><div><small>Outcome</small><b>{record?.outcome||"—"}</b></div><div><small>Cited clauses</small><b>{record?.cited_clause_ids.join(", ")||"—"}</b></div><div><small>Reason codes</small><b>{record?.reason_codes.join(", ")||"—"}</b></div><div><small>Policy source</small>{record?<a href={record.policy_url} target="_blank">Open exact source</a>:<b>—</b>}</div></div><p className="boundary">This is a version-bound review signal, not a payment instruction, legal ruling, or guarantee of refund.</p></section>
 <section className="message"><b>Protocol status</b><p>{message}</p></section><section className="journal"><p className="eyebrow">TRANSACTION PROOF</p><h2>Finalized browser writes</h2>{journal.length?journal.map(x=><a key={x.hash} href={`${EXPLORER}/tx/${x.hash}`} target="_blank"><b>{x.label}</b><code>{x.hash.slice(0,14)}…{x.hash.slice(-8)}</code><span>Explorer ↗</span></a>):<p>No transaction signed in this browser session.</p>}</section></main><footer><img src="/policy-sentinel-logo.png"/><b>PolicyVersion Sentinel</b><p>One claim. One policy version. Grounded clauses.</p>{valid&&<a href={`${EXPLORER}/address/${contract}`} target="_blank">Contract on Explorer</a>}</footer></>}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
